# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N3BLQYPj3zbMk3EssP8d7X7Gu78MKAQI
"""

# 🚀 Advanced Sentiment Analysis Project by Aryan Sharma
# 🌟 HexSoftwares Internship Task 1 - Twitter Sentiment Analysis

!pip install textblob matplotlib

from textblob import TextBlob
import matplotlib.pyplot as plt

print("🤖 AryanBot Sentiment Analyzer Ready!\n")

# --- Predefined demo sentences (aapko input dene ki zarurat nahi) ---
texts = [
    "I love this internship, it is amazing!",
    "The project is very difficult.",
    "I am feeling okay today.",
    "This AI code is fantastic and powerful.",
    "I hate when errors come again and again."
]

# --- Sentiment counters ---
positive = 0
negative = 0
neutral = 0

# --- Sentiment analysis ---
for text in texts:
    blob = TextBlob(text)
    polarity = blob.sentiment.polarity

    if polarity > 0:
        sentiment = "Positive 😀"
        positive += 1
    elif polarity < 0:
        sentiment = "Negative 😡"
        negative += 1
    else:
        sentiment = "Neutral 😐"
        neutral += 1

    print(f"📝 Sentence: {text}")
    print(f"➡️ Detected Sentiment: {sentiment}\n")

# --- Visualization (Graph) ---
labels = ['Positive 😀', 'Negative 😡', 'Neutral 😐']
values = [positive, negative, neutral]

plt.bar(labels, values, color=['green','red','blue'])
plt.title("Sentiment Analysis Result")
plt.xlabel("Sentiment Type")
plt.ylabel("Count")
plt.show()

